---
title: "cross_validation"
author: "Casandra Laney"
date: "2025-11-11"
output: html_document
---

```{r}
library(tidyverse)
library(modelr)
library(mgcv)
```

```{r}
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


```{r}
library(p8105.datasets)

set.seed(1)
```


```{r}
data("lidar")

lidar_df = 
  lidar |> 
  as_tibble() |>
  mutate(id = row_number())

lidar_df |> 
  ggplot(aes(x = range, y = logratio)) + 
  geom_point()
```

# Create Dataframes

```{r}
train_df = sample_frac(lidar_df, size = .8)
test_df = anti_join(lidar_df, train_df, by = "id")

ggplot(train_df, aes(x = range, y = logratio)) + 
  geom_point() + 
  geom_point(data = test_df, color = "red")
```

Fit a few models to the 'train_df'

```{r}
linear_mod = lm(logratio ~ range, data = train_df)
```

Look at this

```{r}
train_df |>
  add_predictions(linear_mod) |>
  ggplot(aes(x = range, y = logratio)) +
  geom_point() +
  geom_line(aes(y = pred), color = 'red')
```

```{r}
linear_mod = lm(logratio ~ range, data = train_df)
smooth_mod = mgcv::gam(logratio ~ s(range), data = train_df)
wiggly_mod = mgcv::gam(logratio ~ s(range, k = 30), sp = 10e-6, data = train_df)
```

```{r}
train_df |> 
  add_predictions(smooth_mod) |> 
  ggplot(aes(x = range, y = logratio)) + 
  geom_point() + 
  geom_line(aes(y = pred), color = "red")
```

Try computing RMSEs

```{r}
rmse(linear_mod, test_df)
rmse(smooth_mod, test_df)
rmse(wiggly_mod, test_df)
```

## Iterate

```{r}
cv_df = 
  crossv_mc(lidar_df, n = 100) |>
  mutate(
    train = map(train, as_tibble),
    test = map(test, as_tibble)
  )
```

Did this work?

```{r}
cv_df |>
  pull(train) |>
  nth(3)
```

Let's fit models over and over

```{r}
cv_df = 
  cv_df |>
  mutate(
    linear_fits = map(train, \(df) lm(logratio~range, data = df)),
    smooth_fits = map(train, \(df) mgcv::gam(logratio~s(range), data = df)),
    wiggly_fits = map(train, \(df) mgcv::gam(logratio~s(range, k = 50), sp = 10e-8, data = df))
  ) |>
  mutate(rmse_linear = map2_dbl(linear_fits, test, rmse),
         rmse_smooth = map2_dbl(smooth_fits, test, rmse),
         rmse_wiggly = map2_dbl(wiggly_fits, test, rmse)
         )
```

Let's try to look at this better

```{r}
cv_df |>
  select(starts_with("rmse")) |>
  pivot_longer(
    everything(),
    names_to = 'model',
    values_to = 'rmse',
    names_prefix = 'rmse_'
  ) |>
  ggplot(aes(x = model, y = rmse)) +
  geom_violin()
```

## Child Growh

```{r}
growth_df =
   read_csv("data/nepalese_children.csv")

```

Weight v arm_c

```{r}
growth_df |>
  ggplot(aes(x = weight, y = armc)) +
  geom_point(alpha = .5)
```

Let's show the models we might use.

```{r}
growth_df =
  growth_df |>
  mutate(
    weight_cp7 = (weight > 7) * (weight - 7)
  )
```

Let's fit three models

```{r}
linear_mod = lm(armc ~ weight, growth_df)
pwl_mod = lm(armc ~ weight + weight_cp7, data = growth_df)
smooth_mod = mgcv::gam(armc ~ s(weight), data = growth_df)
```

```{r}
growth_df |>
  add_predictions(smooth_mod) |>
  ggplot(aes(x = weight, y = armc)) +
  geom_point(alpha = 0.5) +
  geom_line(aes(y = pred), color = "red")
```

Now cross validate!

```{r}
cv_df = 
  crossv_mc(growth_df, n = 100) |>
  mutate(
    train = map(train, as_tibble),
    test = map(test, as_tibble)
  )
```


```{r}
cv_df = 
  cv_df |> 
  mutate(
    linear_mod  = map(train, \(df) lm(armc ~ weight, data = df)),
    pwl_mod     = map(train, \(df) lm(armc ~ weight + weight_cp7, data = df)),
    smooth_mod  = map(train, \(df) mgcv::gam(armc ~ s(weight), data = as_tibble(df)))
    ) |> 
  mutate(
    rmse_linear = map2_dbl(linear_mod, test, rmse),
    rmse_pwl    = map2_dbl(pwl_mod, test, rmse),
    rmse_smooth = map2_dbl(smooth_mod, test, rmse))
```

```{r}
cv_df |>
  select(starts_with("rmse")) |>
  pivot_longer(
    everything(),
    names_to = 'model',
    values_to = 'rmse',
    names_prefix = 'rmse_'
  ) |>
  ggplot(aes(x = model, y = rmse)) +
  geom_violin()
```

